### ISSUE TITLE
Create collab space for this effort

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/package-json-research#1]
@Ethan-Arrowood and @joesepi said they'd create the proposal.

More info on collab spaces here, but collab spaces are basically meant to be a more collaborative working group. https://github.com/openjs-foundation/cross-project-council/blob/main/collaboration-spaces/COLLABORATION_NETWORK.md

**Comment by Ethan-Arrowood** [comment]
email sent <picture data-single-emoji=":sent:" title=":sent:"><img class="emoji" src="https://emoji.slack-edge.com/T0CAQ00TU/sent/f1a8c400534d04a1.png" alt=":sent:" width="20" height="auto" align="absmiddle"></picture>

**Comment by Ethan-Arrowood** [comment]
<picture data-single-emoji=":done:" title=":done:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/done/556da3823bdfab37.png" alt=":done:" align="absmiddle"></picture> https://github.com/openjs-foundation/package-metadata-interoperability-collab-space
